### ISSUE TITLE
Code completeness checklist

### ISSUE THREAD

**Issue by matsumotosan** [andyzfchen/truncatedSVD#3]
Need to complete five main items for the README:
- [ ] specification of dependencies
- [ ] training code
- [ ] evaluation code
- [ ] pre-trained models
- [ ] table of results with precise commands to run/produce the results

Probably a bit different for us since we're not doing neural nets.

Resources: https://paperswithcode.com/rc2020/resources
Code completeness checklist: https://github.com/paperswithcode/releasing-research-code
