### ISSUE TITLE
Final list of to-do's

### ISSUE THREAD

**Issue by matsumotosan** [andyzfchen/truncatedSVD#6]
- [x] BCG X matrix initialization
- [x] README update
- [x] Clean up console message
- [x] Plot runtimes
- [x] Swap order of run_tests (dataset <-> method)
- [x] Print metrics for last singular triplet at end of update
- [x] Clean up notation (i.e. Ak, A_all, A_true)
- [x] Example JSON experiment specs
- [x] Save using np.savez_compressed
- [x] Projection error
- [x] FD projection error bug
